"use strict";
exports.__esModule = true;
var Carro_1 = require("./Carro");
var Moto_1 = require("./Moto");
var Concessionaria_1 = require("./Concessionaria");
var carroA = new Carro_1["default"]('Tipo', 4);
var motoA = new Moto_1["default"]();
var concessionariaA = new Concessionaria_1["default"]('', []);
motoA.acelerar();
console.log(carroA);
console.log(motoA);
console.log(concessionariaA.fornecerHorarioDeFuncionamento());
